# Generated by Django 4.2.3 on 2023-07-06 05:29

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='заголовок')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение')),
                ('annotations1', ckeditor.fields.RichTextField(blank=True, verbose_name='информация')),
                ('annotations2', models.TextField(blank=True, verbose_name='ссылка,если есть')),
                ('is_header_published', models.BooleanField(default=False, verbose_name='Публикация в шапке сайта')),
                ('is_published', models.BooleanField(default=False, verbose_name='Публикация в контактах, карты-не отмечать!!!')),
            ],
            options={
                'verbose_name': 'контакты ',
                'verbose_name_plural': 'Контакты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='Фото')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='примечание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фото',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Graphics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='изображение')),
                ('title', models.CharField(max_length=55, verbose_name='описание изображения')),
                ('note', ckeditor.fields.RichTextField(blank=True, verbose_name='примечание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'графический объект',
                'verbose_name_plural': 'Графика и т.п.',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='Заголовок статьи')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='текст статьи')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Статью',
                'verbose_name_plural': 'Статьи',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Категория услуг')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='основное изображение для услуги')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Краткое  описание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serv_category', to='therapy.servicecategory', verbose_name='Категория услуг')),
            ],
            options={
                'verbose_name': 'Услугв',
                'verbose_name_plural': 'Услуги',
                'ordering': ['time_create', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServicesGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='Фото')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='примечание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('gallery_service_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy.services', verbose_name=' к какой услуге фото')),
            ],
            options={
                'verbose_name': 'фотографию к услуге',
                'verbose_name_plural': 'фото к услуге',
                'ordering': ['gallery_service_link'],
            },
        ),
        migrations.CreateModel(
            name='PostGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='Фото')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='примечание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('gallery_post_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy.post', verbose_name=' к какой статье фото')),
            ],
            options={
                'verbose_name': 'фотографию к статье',
                'verbose_name_plural': 'фото к статье',
                'ordering': ['gallery_post_link'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='post_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_post', to='therapy.services', verbose_name='О какой услуге статья'),
        ),
        migrations.CreateModel(
            name='Coaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Имя')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='портрет')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Кто по жизни')),
                ('is_published', models.BooleanField(default=True, verbose_name='Работает или нет')),
                ('coach_services', models.ManyToManyField(to='therapy.servicecategory', verbose_name='Чему тренирует')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренера',
                'ordering': ['id', 'title'],
            },
        ),
    ]
