# Generated by Django 4.2.3 on 2023-07-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0002_contacts_gallery_graphics_post_servicecategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='services',
            name='duration',
            field=models.CharField(blank=True, default=' - ', max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Цена'),
        ),
    ]
