# Generated by Django 4.2.3 on 2023-07-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0003_alter_services_options_services_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='видео (если есть)'),
        ),
        migrations.AlterField(
            model_name='services',
            name='duration',
            field=models.CharField(blank=True, default=' - ', max_length=255, verbose_name='продолжительность'),
        ),
    ]
