# Generated by Django 4.2.3 on 2023-07-09 16:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0004_gallery_video_alter_services_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Краткое  описание'),
        ),
    ]
