# Generated by Django 4.2.3 on 2023-07-20 05:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0004_gallery_video_alter_services_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Кричащий заголовок')),
                ('sub_title', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок, если нужен')),
                ('about', models.CharField(blank=True, max_length=100, verbose_name='Про что(не выводится на экран)')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='рекламная иконка, если нужна')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='изображение к рекламной статье, если есть')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='текст рекламы')),
                ('is_published', models.BooleanField(default=False, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Акции и реклама',
                'verbose_name_plural': 'Акции',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='gallery_link',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='cat_photo', to='therapy.servicecategory', verbose_name='к какой категории фото'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Краткое  описание'),
        ),
    ]
