# Generated by Django 4.2.3 on 2023-07-11 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0005_servicecategory_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='gallery_link',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='therapy.servicecategory', verbose_name='к какой категории фото'),
        ),
    ]
