# Generated by Django 4.2.3 on 2023-08-03 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0005_commercial_gallery_gallery_link_and_more'),
        ('therapy', '0008_alter_gallery_gallery_link'),
    ]

    operations = [
    ]
