# Generated by Django 4.2.3 on 2023-08-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0012_remove_commercial_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='рекламная иконка - не использовать!!!'),
        ),
    ]
