# Generated by Django 4.2.3 on 2023-08-03 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0013_commercial_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Заголовок')),
                ('sub_title', models.CharField(db_index=True, max_length=255, verbose_name='подзаголовок')),
                ('abonement_duration', models.CharField(blank=True, default=' - ', max_length=255, verbose_name='кол-во занятий или сеансов')),
                ('abonement_price', models.PositiveIntegerField(default=0, null=True, verbose_name='Цена абонемента')),
                ('validity', models.CharField(max_length=100, verbose_name='срок действия')),
                ('is_published', models.BooleanField(default=False, verbose_name='Публикация')),
                ('service_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy.services', verbose_name='к какой  услуге относится')),
            ],
            options={
                'verbose_name': 'Абонемет',
                'verbose_name_plural': 'Абонементы',
                'ordering': ['id'],
            },
        ),
    ]
